# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Robert Wilson
title: Bioinformatician and Software Developer
email: robert.s.wilson1996@gmail.com
website: www.github.com/rswilson1/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: @robthebotanist
github_username:  rswilson1
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: rswilson1
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Robert and I'm a trainee clinical bioinformatician currently working for NHS (East Genomics).
  As well as running bioinformatics workflows, I also have experience making bespokes web apps (such as an interactive dashboard to monitor spending) and tailored python scripts for manipulating datasets.
  I have a strong background in genomics with an integrated master's in Plant Sciences with a focus on genomics and transcriptomics.

  I am most skilled in: <mark>Python</mark> <mark>R</mark> <mark>Cloud-computing with DNAnexus</mark> and <mark>Genomics</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Genomics England
        link: https://www.genomicsengland.co.uk/
        # link_text: Genomics England
        sub_title: Labortory Technician
        caption: February 2021 - September 2021
        quote: >
          High-throughput sequencing for R&D into long-read sequencing for the genomic medicine service.
        description: | # this will include new lines to allow paragraphs
            At Genomics England, I developed protocols and train colleagues for high-throughput sample preparation and sequencing using Oxford Nanopore Promethion.
            I also produced graphs for visualising data from the Labortory to guide our development.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Topic Biosciences
        link: https://tropic.bio/
        # link_text: https://tropic.bio
        sub_title: Labortory Technician
        caption: November 2019 - February 2021
        quote: >
          Solving food security for the future with genomics and CRISPR.
        description: | # this will include new lines to allow paragraphs
            At Tropic, I developed a lot of Labortory skills such as: cloning, DNA extractions, cell-culture and many more. I also developed my skills in data analysis as I was responsible for producing graphs to show the results of experiments and implemented scripts to automate repetitive tasks.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Sheffield
        caption: 2015 - 2019
        sub_title: MBiolSci in Plant Sciences
        quote: >
          With a focus on data science (using R), genomics and transcriptomics.
        description: | # this will include new lines to allow paragraphs
          During my time at Sheffield I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in genomics and software engineering some of my other interests and hobbies are:
      - Cycling
      - Rock climbing
      - Hiking

      I also love nature and landscapes like this one:
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
